config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :slides
=======
  resources :cars
  get 'welcome/index'

>>>>>>> dcd91b76b1157917ea719c0b3e814cfa2962036b
  resources :statements
  devise_for :users
  
  resources :slides, only: [:index]
 namespace :admin do
    resources :slides
    root 'slides#index'
 end
 root 'slides#index'
  root 'welcome#index'

end

app/models/statement.rb
class Statement < ActiveRecord::Base
end
class User < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :set_statement, only: [:show, :edit, :update, :destroy]

  # GET /statements
  # GET /statements.json
  def index
    @statements = Statement.all
  end

  # GET /statements/1
  # GET /statements/1.json
  def show
  end

  # GET /statements/new
  def new
    @statement = Statement.new
  end

  # GET /statements/1/edit
  def edit
  end

  # POST /statements
  # POST /statements.json
  def create
    @statement = Statement.new(statement_params)

    respond_to do |format|
      if @statement.save
        format.html { redirect_to @statement, notice: 'Statement was successfully created.' }
        format.json { render :show, status: :created, location: @statement }
      else
        format.html { render :new }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statements/1
  # PATCH/PUT /statements/1.json
  def update
    respond_to do |format|
      if @statement.update(statement_params)
        format.html { redirect_to @statement, notice: 'Statement was successfully updated.' }
        format.json { render :show, status: :ok, location: @statement }
      else
        format.html { render :edit }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statements/1
  # DELETE /statements/1.json
  def destroy
    @statement.destroy
    respond_to do |format|
      format.html { redirect_to statements_url, notice: 'Statement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statement
      @statement = Statement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statement_params
      params.require(:statement).permit(:date, :reason, :nb_km, :taxe_coef, :ride, :start, :arrival, :user_id)
    end
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/statements/_form.html.erb
<%= form_for(@statement) do |f| %>
  <% if @statement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statement.errors.count, "error") %> prohibited this statement from being saved:</h2>

      <ul>
      <% @statement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="field">
    <%= f.label :nb_km %><br>
    <%= f.number_field :nb_km %>
  </div>
  <div class="field">
    <%= f.label :taxe_coef %><br>
    <%= f.number_field :taxe_coef %>
  </div>
  <div class="field">
    <%= f.label :ride %><br>
    <%= f.number_field :ride %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.text_field :start %>
  </div>
  <div class="field">
    <%= f.label :arrival %><br>
    <%= f.text_field :arrival %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statements/edit.html.erb
<h1 class="text-center jumbotron">Editing Statement</h1>
<div class="text-center">
<%= render 'form' %>

<%= link_to 'Show', @statement %> |
<%= link_to 'Back', statements_path %>
</div>

app/views/statements/index.html.erb
<br>
<div class="jumbotron text-center">
<h1>Listing tajets</h1>
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
<br>
  Logged in as <strong><%= current_user.email %></strong>.
<br>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
<% end %>
</div>
<div class="text-center">
<div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary active">
    <input type="radio" name="options" id="option1" autocomplete="off" checked> Janvier
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="option2" autocomplete="off"> Février
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Mars
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Avril
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Mai
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Juin
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Juillet
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Aout
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Séptembre
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Octobre
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Novembre
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Décembre
  </label>
</div>
</div>*

<<<<<<< HEAD
<h1>Listing Statements</h1>
<hr>
<table>
=======
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Mes véhicules
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
  </ul>
</div>

<br>
<table class="table table-hover">
>>>>>>> dcd91b76b1157917ea719c0b3e814cfa2962036b
  <thead>
    <tr>
      <th>Date</th>
      <th>Raison</th>
      <th>Nbr. km</th>
      <th>Taxe coef.</th>
      <th>Ride</th>
      <th>Départ</th>
      <th>Arrivé</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statements.each do |statement| %>
      <tr>
        <td><%= statement.date %></td>
        <td><%= statement.reason %></td>
        <td><%= statement.nb_km %></td>
        <td><%= statement.taxe_coef %></td>
        <td><%= statement.ride %></td>
        <td><%= statement.start %></td>
        <td><%= statement.arrival %></td>
        <td><%= statement.user_id %></td>
        <td><%= link_to 'Show', statement %> <span class="glyphicon glyphicon-search" aria-hidden="true"></span></td>
        <td><%= link_to 'Edit', edit_statement_path(statement) %> <span class="glyphicon glyphicon-edit" aria-hidden="true"></span></td>
        <td><%= link_to 'Destroy', statement, method: :delete, data: { confirm: 'Are you sure?' } %> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></td>
      </tr>
    <% end %>
  </tbody>
</table>
<<<<<<< HEAD


=======
>>>>>>> dcd91b76b1157917ea719c0b3e814cfa2962036b
<br>
<button class="btn btn-primary center-block">Export</button>
<br>
<div class="text-center">
<%= link_to 'New Statement', new_statement_path %>
</div>

app/views/statements/new.html.erb
<<<<<<< HEAD
<h1>New Statement</h1>
<hr>
<%= render 'form' %>

<%= link_to 'Back', statements_path %>
<%= simple_form_for @user, url: users_path do |form| %>
  <%= form.input :avatar, as: :file %>
<% end %>
=======
<div class="text-center">
<h1 class="jumbotron">New Statement</h1>

<%= render 'form' %>

<%= link_to 'Back', statements_path %>
</div>
>>>>>>> dcd91b76b1157917ea719c0b3e814cfa2962036b

app/views/statements/show.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
<p>
  <strong>Date:</strong>
  <%= @statement.date %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @statement.reason %>
</p>

<p>
  <strong>Nb km:</strong>
  <%= @statement.nb_km %>
</p>

<p>
  <strong>Taxe coef:</strong>
  <%= @statement.taxe_coef %>
</p>

<p>
  <strong>Ride:</strong>
  <%= @statement.ride %>
</p>

<p>
  <strong>Start:</strong>
  <%= @statement.start %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @statement.arrival %>
</p>

<p>
  <strong>User:</strong>
  <%= @statement.user_id %>
</p>

<%= link_to 'Edit', edit_statement_path(@statement) %> |
<%= link_to 'Back', statements_path %>
</div>