config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :slides
=======
  resources :cars
  get 'welcome/index'

>>>>>>> dcd91b76b1157917ea719c0b3e814cfa2962036b
  resources :statements
  devise_for :users
  
  resources :slides, only: [:index]
 namespace :admin do
    resources :slides
    root 'slides#index'
 end
 root 'slides#index'
  root 'welcome#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :users
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = if current_user.admin?
      Car.all
    else
      Car.Where(users_id: current_user)
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:brand, :model, :fiscal_power, :vehicle_type, :users_id)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :fiscal_power %><br>
    <%= f.number_field :fiscal_power %>
  </div>
  <div class="field">
    <%= f.label :vehicle_type %><br>
    <%= f.select :vehicle_type, [['Car', 'car'], ['Bike', 'bike'], ['< 50', '< 50']] %>
  </div>
  <div class="field">
    <%= f.label :users_id %><br>
    <%= f.text_field :users_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="jumbotron text-center">Listing Cars</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Fiscal power</th>
      <th>Vehicle type</th>
      <th>Users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.fiscal_power %></td>
        <td><%= car.vehicle_type %></td>
        <td><%= car.users %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1 class="jumbotron text-center">New Car</h1>
<div class="text-center">
<%= render 'form' %>

<%= link_to 'Back', cars_path %>
</div>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Fiscal power:</strong>
  <%= @car.fiscal_power %>
</p>

<p>
  <strong>Vehicle type:</strong>
  <%= @car.vehicle_type %>
</p>

<p>
  <strong>Users:</strong>
  <%= @car.users %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>